package com.example.homework_1.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.homework_1.repository.DataRepository
import com.example.homework_1.repository.FilmGenerator
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue

@Composable
fun FirstScreen(
    repository: DataRepository,
    onNavigateToSecond: () -> Unit
) {
    var userInput by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    val generator = remember { FilmGenerator() }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        OutlinedTextField(
            value = userInput,
            onValueChange = { newText ->
                if (newText.all { it.isDigit() }) {
                    userInput = newText
                }
            },
            label = { Text("Введите количество фильмов") }
        )

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            enabled = userInput.toIntOrNull() != null && userInput.toInt() > 0,
            onClick = {
                val count = userInput.toInt()
                val films = generator.generate(count)
                repository.saveFilms(films)
                isGenerated = true
            }
        ) {
            Text("Сгенерировать")
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            enabled = isGenerated,
            onClick = { onNavigateToSecond() }
        ) {
            Text("Показать список")
        }
    }
}